### ISSUE TITLE
Silk touch does not work

### ISSUE THREAD

**Issue by leamir** [cailir/cDrops2Inv#12]
**Describe the bug**
Silk touch does not works
**To Reproduce**
1. Get a enchanted item with silk touch
2. try to break a grass block, or anything that should be affected with silk touch

**Expected behavior**
The grass block/other block comming

**Comment by cailir** [comment]
Hello,
I'll need more information. Like the Plugin version, you can check it using the `/version cDrops2Inv` command.

**Comment by leamir** [comment]
the server is using the plugin version 1.2.1-DEV
